#!/bin/bash

#
# Install npm packages using the alterate versions of node and npm
# that were installed by the pre_build hook.
#
# This hook runs after pre_build, but before deploy. It is responsible
# for getting the appliation into a runnable state.
#
# Note that OpenShift environment variables have a trailing slash.
#

echo "Starting build hook"

START=$(date +'%s')

cd $OPENSHIFT_REPO_DIR

if [[ -f "package.json.bak" ]]; then
    mv package.json.bak package.json
fi

npm install --production
npm prune --production

DURATION=$(($(date +'%s') - START))

echo "Finished build hook in $DURATION seconds"
