#!/usr/bin/env node

/**
 * Populate the file env.json with modified values derived from
 * OpenShift environment variables
 *
 * This hook runs after pre_build and build, and occurs right before
 * the application is started. Anything needed to get the application
 * to start should be done here.
 *
 * Note that OpenShift environment variables have a trailing slash.
 */

var fs = require('fs');

var start = new Date();

console.log('Starting deploy hook');

var appEnv = {};

appEnv.NOTIFIER_LOG = process.env.OPENSHIFT_LOG_DIR + 'notifier.log';
appEnv.NOTIFIER_LOG_LEVEL = 'warn';
appEnv.NOTIFIER_HTTP_IP = process.env.OPENSHIFT_NODEJS_IP;
appEnv.NOTIFIER_HTTP_PORT = process.env.OPENSHIFT_NODEJS_PORT;
appEnv.NOTIFIER_WEBSOCKET_PORT = '8443';
appEnv.NOTIFIER_FORCE_HTTPS = 'true';
appEnv.NOTIFIER_DB: "openshift",

// Login credentials are intentionally omitted. They will be populated
// from server.js
appEnv.NOTIFIER_DB_CONFIG = {
    "openshift": {
        "sequelize": {
            "host": process.env.OPENSHIFT_MYSQL_DB_HOST,
            "port": process.env.OPENSHIFT_MYSQL_DB_PORT,
            "dialect": "mysql"
        }
    }
}

var appEnvString = JSON.stringify(appEnv, null, 2);

fs.writeFile(process.env.OPENSHIFT_REPO_DIR + 'env.json', appEnvString, function (err) {
    if (err) {
        console.log(err);
    }

    console.log('env.json: ' + appEnvString);
    console.log('Finished deploy hook in ' + (new Date().getTime() - start.getTime()) + ' seconds');
});
