#!/bin/bash

#
# Build the web UI and clean up unnecessary files.
#
# This is the last hook. The node server is already running at this
# point.
#
# Note that OpenShift environment variables have a trailing slash.
#

echo "Starting post_deploy hook"

START=$(date +'%s')

cd $OPENSHIFT_REPO_DIR

grunt build:full

rm env-sample-*.json
rm env-test.json
rm -rf test

DURATION=$(($(date +'%s') - START))

echo "Finished post_deploy hook in $DURATION seconds"
