#!/bin/bash

#
# Create the application database if it does not exist
#
# This is the last hook. The node server is already running at this
# point. See https://developers.openshift.com/en/managing-action-hooks.html
#
# Note that OpenShift environment variables have a trailing slash.
#

echo "Starting post_deploy hook"

# Database creation
DB_EXISTS=$(mysql -h$OPENSHIFT_MYSQL_DB_HOST -u$OPENSHIFT_MYSQL_DB_USERNAME -p$OPENSHIFT_MYSQL_DB_PASSWORD -B -e 'show databases' | grep -c $NOTIFIER_DB_NAME)

if [[ $DB_EXISTS == 0 ]]; then
    echo -n "MySQL database does not exist, creating..."
    mysqladmin -h$OPENSHIFT_MYSQL_DB_HOST -u$OPENSHIFT_MYSQL_DB_USERNAME -p$OPENSHIFT_MYSQL_DB_PASSWORD create $NOTIFIER_DB_NAME
    echo "done"
else
    echo "The MySQL database exists, will not attempt to create."
fi

START=$(date +'%s')

cd $OPENSHIFT_REPO_DIR

# Disable sequelize migration due to error about js-v8flags during deployment
#grunt migrate

rm env-sample.json
rm env-test.json
rm -rf test
rm -f migration-config.json

DURATION=$(($(date +'%s') - START))

echo "Finished post_deploy hook in $DURATION seconds"
