#!/bin/bash

#
# Build the application
#

echo "Starting post_deploy hook"

START=$(date +'%s')

cd $OPENSHIFT_REPO_DIR

grunt build:full

rm env-sample-*.json
rm env-test.json
rm -rf test

DURATION=$(($(date +'%s') - START))

echo "Finished post_deploy hook in $DURATION seconds"
