#!/usr/bin/env bash

set -eu

WORK_DIR=$(mktemp -p . -d)

cleanup() {
    rm -rf "$WORK_DIR"
}

trap "cleanup" EXIT


LINT_TS_UI=0
LINT_TS_SERVER=0
LINT_TS_WORKER=0

echo "Runing pre-commit hook..."

# Copy staged files to the work directory.
#
# This ensures the files being checked are the files being committed.
git checkout-index --prefix="$WORK_DIR/" -af


# Walk through the staged files and lint the copies in the work
# directory.  The filter argument excludes deleted, copied, and
# renamed files.
for STAGED_FILE in $(git diff --cached --name-only --diff-filter=dcr); do
    FILE_EXTENSION="${STAGED_FILE##*.}"

    # JSON
    if [[ "$FILE_EXTENSION" == "json" ]]; then
        node "$WORK_DIR/$STAGED_FILE"
    fi

    # Less
    if [[ "$FILE_EXTENSION" == "less" ]]; then
        node_modules/.bin/stylelint "$WORK_DIR/$STAGED_FILE"
    fi

    # Typescript
    if [[ "$FILE_EXTENSION" == "ts" ]]; then
        if [[ "$STAGED_FILE" == ui/* ]]; then
            LINT_TS_UI=1
        fi

        if [[ "$STAGED_FILE" == server/* ]]; then
            LINT_TS_SERVER=1
        fi

        if [[ "$STAGED_FILE" == worker/* ]]; then
            LINT_TS_WORKER=1
        fi
    fi
done

if [ "$LINT_TS_UI" = 1 ]; then
    echo "Linting ui..."
    node_modules/.bin/tsc --noEmit -p "$WORK_DIR/ui"
	node_modules/.bin/eslint "$WORK_DIR/ui" --ext .ts
fi

if [ "$LINT_TS_SERVER" = 1 ]; then
    echo "Linting server..."
	node_modules/.bin/tsc --noEmit -p "$WORK_DIR/server"
	node_modules/.bin/eslint "$WORK_DIR/server" --ext .ts
fi

if [ "$LINT_TS_WORKER" = 1 ]; then
    echo "Linting worker..."
	node_modules/.bin/tsc --noEmit -p "$WORK_DIR/worker"
	node_modules/.bin/eslint "$WORK_DIR/worker" --ext .ts
fi
