#!/bin/bash

#
# Create a local backup of this application's MySQL database
#

CURRENT_DATE=$(date +"%Y%m%d-%H%M")

DB_NAME=notifier

BACKUP_DIR="$OPENSHIFT_DATA_DIR/backup-mysql"

mkdir -p "$BACKUP_DIR"

mysqldump -u$OPENSHIFT_MYSQL_DB_USERNAME  -p$OPENSHIFT_MYSQL_DB_PASSWORD -h$OPENSHIFT_MYSQL_DB_HOST $DB_NAME | gzip > "$BACKUP_DIR/$CURRENT_DATE.$DB_NAME.sql.gz"

find $BACKUP_DIR/* -mtime +3 -exec rm {} \;

