---
- hosts: notifier
  vars:
    application_user: nobody
    application_group: nobody
    application_port: 8080
    installation_directory: /var/www/notifier
    nodejs_path: /usr/bin/node
  tasks:
  - name: Rsync the application
    become: true
    synchronize:
      src: "../build/"
      dest: "{{ installation_directory }}"
      delete: yes
      recursive: true

  - name: Set permissions on application root
    become: true
    file:
      path: "{{ installation_directory }}"
      recurse: yes
      owner: "{{ application_user }}"
      group: "{{ application_group }}"

  - name: Populate the systemd service
    become: true
    template:
      src: "notifer.service.j2"
      dest: "/etc/systemd/system/notifier.service"

  - name: Enable systemd service
    become: true
    systemd:
      name: notifier
      enabled: yes
      masked: no
      daemon_reload: yes

  - name: Restart the server
    become: true
    systemd:
      name: notifier
      state: restarted

  - name: Wait for server to come up
    wait_for:
      host: 0.0.0.0
      port: "{{ application_port }}"
      state: started

...
