---
- hosts: all
  vars:
    application_user: notifier
    installation_directory: /srv/notifier-prod
    nodejs_path: /usr/local/bin/node
  tasks:
  - name: Create the application user
    become: true
    user:
      state=present
      groups=""
      name="{{ application_user }}"
      createhome=no
      home="{{ installation_directory }}"
      shell="/usr/sbin/nologin"
      system=yes

  - name: Create the application directories
    become: true
    file:
      path: "{{ item }}"
      state: directory
      owner: "{{ application_user }}"
      group: "{{ application_user }}"
      mode: 0700
    with_items:
      - "{{ installation_directory }}"
      - /var/log/notifier

  - name: Rsync
    become: true
    become_user: "{{ application_user }}"
    synchronize:
      src: "../notifier/"
      dest: "{{ installation_directory }}"
      delete: true
      recursive: true

  - name: Populate the systemd unit
    become: true
    template:
      src: "notifer.service.j2"
      dest: "/etc/systemd/system/notifier.service"
    notify: Reload systemd

  - name: Enable systemd service
    become: true
    command: systemctl enable notifier

  - name: Restart the application
    become: true
    command: systemctl restart notifier

  handlers:
    - name: Reload systemd
      become: true
      command: systemctl daemon-reload

...
